spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: proyectos
          uri: http://localhost:8082
          predicates:
            - Path=/proyectos/**

server:
  port: 8080
